# Generated by Django 5.0.7 on 2024-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('dato', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
